{
 "title": "Monitoramento Concentradores Lojas",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Métricas de todos os Concentradores ",
   "type": "timeseries",
   "description": "Monitoramento de todos os concentradores",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip=\"172.16.101.23\", ip_version=\"4\", job=\"Ping_Exporter\", target=\"172.16.101.23\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.12.21\", target=\"192.168.12.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip=\"192.168.12.21\", ip_version=\"4\", job=\"Ping_Exporter\", target=\"192.168.12.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buritis 20",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.20.21\", target=\"192.168.20.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tamóios 02",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", job=\"Ping_Exporter\", ip_version=\"4\", ip=\"192.168.3.31\", target=\"192.168.3.31\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prudente de Moraes",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.30.21\", target=\"192.168.30.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lojas Teste",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.40.21\", target=\"192.168.40.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Caetés 50",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.50.21\", target=\"192.168.50.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Túpis 05",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.205.21\", target=\"192.168.205.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uberlândia 96",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.96.21\", target=\"192.168.96.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Divinópolis 105",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.105.21\", target=\"192.168.105.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carijós 01",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.2.21\", target=\"192.168.2.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Betim 13",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.13.21\", target=\"192.168.13.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "curitiba 14",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.14.21\", target=\"192.168.14.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Paraná 15",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.15.21\", target=\"192.168.15.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lagoinha 16",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.16.41\", target=\"192.168.16.41\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Via do minério 17",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.7.21\", target=\"192.168.7.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sete Lagoas 18",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.18.21\", target=\"192.168.18.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pedro Leopoldo 19",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.19.21\", target=\"192.168.19.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Venda Nova 12",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.12.21\", target=\"192.168.12.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shopping Estação 22",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.22.21\", target=\"192.168.22.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vila da Serra 23",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.23.21\", target=\"192.168.23.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minas Shopping 24",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.24.21\", target=\"192.168.24.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shopping Partage 25",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.25.21\", target=\"192.168.25.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Itaú Power Shopping 26",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.26.21\", target=\"192.168.26.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shopping Contagem 27",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.27.21\", target=\"192.168.27.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Céu Azul 28",
   "type": "stat",
   "description": "teste monitoramento de ativos",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.28.21\", target=\"192.168.28.21\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}