{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Concentrador",
   "type": "stat",
   "description": "monitoramento de ping",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"192.168.18.171:9427\", ip=\"192.168.18.170\", ip_version=\"4\", job=\"Ping_Exporter\", target=\"192.168.18.170\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Venda Nova 03",
   "type": "stat",
   "description": "monitoramento de ping",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"192.168.18.171:9427\", ip=\"192.168.18.177\", ip_version=\"4\", job=\"Ping_Exporter\", target=\"192.168.18.177\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tamóios 02",
   "type": "stat",
   "description": "Monitoramento de Ping dos Concentradores Lojas.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"192.168.18.171:9427\", ip=\"192.168.18.180\", ip_version=\"4\", job=\"Ping_Exporter\", target=\"192.168.18.180\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}