{
 "title": "Monitoramento Concentradores Lojas",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Lojas Rede",
   "type": "text",
   "description": "Lojas Rede",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMzMxMzVhb2Z5cTA3bW8wZXFnNGl5YXhicTU2enVjZ3lqczd2aWljYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/9MqvGXCPC7rLcX3A2r/giphy.gif\"/>"
   }
  },
  {
   "title": "Métricas de todos os Concentradores ",
   "type": "timeseries",
   "description": "Monitoramento de todos os concentradores",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.2.21\", target=\"192.168.2.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.3.31\", target=\"192.168.3.31\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.4.21\", target=\"192.168.4.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.100.21\", target=\"192.168.100.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.205.21\", target=\"192.168.205.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.6.21\", target=\"192.168.6.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.7.21\", target=\"192.168.7.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.8.21\", target=\"192.168.8.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.9.21\", target=\"192.168.9.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.1.126\", target=\"192.168.1.126\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.12.21\", target=\"192.168.12.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.13.21\", target=\"192.168.13.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.14.21\", target=\"192.168.14.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.15.21\", target=\"192.168.15.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.16.41\", target=\"192.168.16.41\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.18.21\", target=\"192.168.18.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.19.21\", target=\"192.168.19.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.20.21\", target=\"192.168.20.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.22.21\", target=\"192.168.22.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.23.21\", target=\"192.168.23.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.24.21\", target=\"192.168.24.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.25.21\", target=\"192.168.25.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.26.21\", target=\"192.168.26.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.27.21\", target=\"192.168.27.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.28.21\", target=\"192.168.28.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.30.21\", target=\"192.168.30.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.31.21\", target=\"192.168.31.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.32.21\", target=\"192.168.32.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.33.21\", target=\"192.168.33.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.35.21\", target=\"192.168.35.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.37.21\", target=\"192.168.37.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.38.21\", target=\"192.168.38.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.39.21\", target=\"192.168.39.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.40.21\", target=\"192.168.40.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.41.21\", target=\"192.168.41.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.42.21\", target=\"192.168.42.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.43.21\", target=\"192.168.43.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.44.21\", target=\"192.168.44.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.45.21\", target=\"192.168.45.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.47.21\", target=\"192.168.47.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.49.21\", target=\"192.168.49.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.50.21\", target=\"192.168.50.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.54.21\", target=\"192.168.54.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.55.21\", target=\"192.168.55.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.56.21\", target=\"192.168.56.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.57.21\", target=\"192.168.57.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.58.21\", target=\"192.168.58.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.59.21\", target=\"192.168.59.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.60.21\", target=\"192.168.60.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"172.16.122.13\", target=\"172.16.122.13\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.62.21\", target=\"192.168.62.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.63.21\", target=\"192.168.63.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.64.21\", target=\"192.168.64.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.65.21\", target=\"192.168.65.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.67.21\", target=\"192.168.67.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.68.21\", target=\"192.168.68.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.69.21\", target=\"192.168.69.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.70.21\", target=\"192.168.70.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.71.21\", target=\"192.168.71.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.72.21\", target=\"192.168.72.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.73.21\", target=\"192.168.73.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.74.21\", target=\"192.168.74.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.75.21\", target=\"192.168.75.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.77.21\", target=\"192.168.77.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.78.21\", target=\"192.168.78.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.79.21\", target=\"192.168.79.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.1.130\", target=\"192.168.1.130\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.80.21\", target=\"192.168.80.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.81.21\", target=\"192.168.81.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.85.21\", target=\"192.168.85.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.86.21\", target=\"192.168.86.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.87.21\", target=\"192.168.87.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.89.21\", target=\"192.168.89.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.94.21\", target=\"192.168.94.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.95.21\", target=\"192.168.95.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.96.21\", target=\"192.168.96.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.97.21\", target=\"192.168.97.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"10.1.27.21\", target=\"10.1.27.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.104.21\", target=\"192.168.104.21\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.105.21\", target=\"192.168.105.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carijós 01",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.2.21\", target=\"192.168.2.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tamóios 02",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", job=\"Ping_Exporter\", ip_version=\"4\", ip=\"192.168.3.31\", target=\"192.168.3.31\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Venda Nova 03",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.4.21\", target=\"192.168.4.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rio de Janeiro 04",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.40.21\", target=\"192.168.40.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Túpis 05",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.205.21\", target=\"192.168.205.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Eldorado 06",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.5.21\", target=\"192.168.5.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Paraná 07",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.6.21\", target=\"192.168.6.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Savassi 08",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.8.21\", target=\"192.168.8.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tupinambás 09",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.9.21\", target=\"192.168.9.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Venda Nova 12",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.12.21\", target=\"192.168.12.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Betim 13",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.13.21\", target=\"192.168.13.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "curitiba 14",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.14.21\", target=\"192.168.14.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Paraná 15",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.15.21\", target=\"192.168.15.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lagoinha 16",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.16.41\", target=\"192.168.16.41\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Via do minério 17",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.7.21\", target=\"192.168.7.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sete Lagoas 18",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.18.21\", target=\"192.168.18.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pedro Leopoldo 19",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.19.21\", target=\"192.168.19.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buritis 20",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.20.21\", target=\"192.168.20.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shopping Estação 22",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.22.21\", target=\"192.168.22.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vila da Serra 23",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.23.21\", target=\"192.168.23.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minas Shopping 24",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.24.21\", target=\"192.168.24.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shopping Partage 25",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.25.21\", target=\"192.168.25.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shopping Itaú 26",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.26.21\", target=\"192.168.26.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shopping Contagem 27",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.27.21\", target=\"192.168.27.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Céu Azul 28",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.28.21\", target=\"192.168.28.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prudente de Moraes",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.30.21\", target=\"192.168.30.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Betânia 31",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.31.21\", target=\"192.168.31.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conselheiro Lafaiete 32",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.32.21\", target=\"192.168.32.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "São Caetano 33",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.33.21\", target=\"192.168.33.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Abílio Machado 35",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.35.21\", target=\"192.168.35.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shopping Del Rey 37",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.37.21\", target=\"192.168.37.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barbacena 38",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.38.21\", target=\"192.168.38.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Juiz de Fora 39",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.39.21\", target=\"192.168.39.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Juiz de Fora 40",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.40.21\", target=\"192.168.40.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ribeirão das Neves 41",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.41.21\", target=\"192.168.41.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Divinópolis 42",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.42.21\", target=\"192.168.42.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nova Contagem 43",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.43.21\", target=\"192.168.43.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pará de Minas 44",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.44.21\", target=\"192.168.44.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Governador Valadares 45",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.1.43\", target=\"192.168.1.43\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shopping Estação 47",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.47.21\", target=\"192.168.47.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waldomiro Lobo 49",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.49.21\", target=\"192.168.49.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Caetés 50",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.50.21\", target=\"192.168.50.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Santa Luzia 52",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.11.21\", target=\"192.168.11.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barreiro 53",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"10.1.27.21\", target=\"10.1.27.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carijós 54",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.54.21\", target=\"192.168.54.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Savassi 55",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.55.21\", target=\"192.168.55.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tiradentes 56",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.56.21\", target=\"192.168.56.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ibirité 57",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.57.21\", target=\"192.168.57.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Santa Luzia 58",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.58.21\", target=\"192.168.58.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barreiro 59",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.59.21\", target=\"192.168.59.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barro Preto 60",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.60.21\", target=\"192.168.60.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Center Minas 61 ",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"172.16.122.13\", target=\"172.16.122.13\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shopping Cidade 62",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.62.21\", target=\"192.168.62.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sete Lagoa 63",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.63.21\", target=\"192.168.63.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Veneza 64",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.64.21\", target=\"192.168.64.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Floresta 65",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.65.21\", target=\"192.168.65.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Barreiro 67",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.67.21\", target=\"192.168.67.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Santa Mônica 68",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.68.21\", target=\"192.168.68.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cidade Nova 69",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.69.21\", target=\"192.168.69.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Montes Claros 70",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.70.21\", target=\"192.168.70.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Castelo 71",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.71.21\", target=\"192.168.71.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pouso Alegre 72",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.72.21\", target=\"192.168.72.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ipatinga 73",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.73.21\", target=\"192.168.73.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Andradas 74",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.74.21\", target=\"192.168.74.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uberlândia 75",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.75.21\", target=\"192.168.75.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uberaba 76",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.76.21\", target=\"192.168.76.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duval de Barros 77",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.77.21\", target=\"192.168.77.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lavras 78",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.78.21\", target=\"192.168.78.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Morro Alto 79",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.79.21\", target=\"192.168.79.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lagoa Santa 80",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.80.21\", target=\"192.168.80.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Só Marcas 81",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.81.21\", target=\"192.168.81.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Araxa 85",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.85.21\", target=\"192.168.85.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Patos de Minas 86",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.86.21\", target=\"192.168.86.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Santa Inês 87",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.87.21\", target=\"192.168.87.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Juiz de Fora Halfeld 89",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.89.21\", target=\"192.168.89.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uberlândia 94",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.94.21\", target=\"192.168.94.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dona Clara 95",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.95.21\", target=\"192.168.95.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uberlândia Center 96",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.96.21\", target=\"192.168.96.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Montes Claros 97",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.1.57\", target=\"192.168.1.57\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ecommerce 100",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.100.21\", target=\"192.168.100.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Divinópolis 104",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.104.21\", target=\"192.168.104.21\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jardim Alterosa 105",
   "type": "stat",
   "description": "Monitoramento de todos os concentradores lojas.\nAmbiente de provisionado por Kaique Costa. Incluindo criação de WorkLab de homologação de projetos Service-Desk, servidor proxmox, e servidor central.\nno servidor central foi realizado o deploy do grafana que está rodando em docker. No servidor proxmox está rodando a VM que hospeda o servidor Prometheus.\nIP proxmox: 172.16.101.205\nIP Prometheus: 172.16.101.13\nIP Servidor Central 172.16.101.210\nEric Oliveira  trabalhando em conjunto  e dando foco total no design do dashboard no grafana.\nMenções Honrosas:\nLuis Fonseca,\nKeyla Coelho,\nFelipe Silva ,\nWelerson,\nvitor oliveira,\nMarco Salles.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_loss_ratio{instance=\"172.16.101.13:9427\", ip_version=\"4\", job=\"Ping_Exporter\", ip=\"192.168.105.21\", target=\"192.168.105.21\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}